version: '3.9'

services:
  #  appbot itself
  appbot:
    build: .
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    networks:
      - appbot_net
    restart: always
    command: npm run start:dev
    environment:
      REDIS_PASSWORD: ''

  # postgres database
  postgres:
    image: postgres:15
    env_file:
      - .postgres.env
    ports:
      - '5432:5432'
    networks:
      - appbot_net
    restart: always

  redis:
    image: redis:7
    ports:
      - '6379:6379'
    networks:
      - appbot_net
    restart: always
    # change the password on your instance
    command: redis-server /usr/local/etc/redis/redis.conf --loglevel debug --protected-mode no
    volumes:
      - ./redisconf:/usr/local/etc/redis:r

# internal network
networks:
  appbot_net:
