version: '3.9'

volumes:
  scylla_db: {}

networks:
  appbot: {}

services:
  appbot:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - scylla
    networks:
      - appbot

  scylla:
    image: scylladb/scylla
    restart: unless-stopped
    volumes:
      - scylla_db:/var/lib/scylla
    env_file:
      - .env
    command:
      - --api-address 0.0.0.0
    ports:
      - 9042
      - 10000
    networks:
      - appbot
